### ISSUE TITLE
Pypy 3.5 is broken on Travis-CI

### ISSUE THREAD

**Issue by sybrenstuvel** [sybrenstuvel/python-rsa#131]
Currently Pypy 3.5 is broken on Travis-CI, so I've disabled it in `.travis.yml`. You can uncomment it in there, commit in a branch, and push it to Github to check whether this is still the case. For me it stopped with this error:

```
$ pipenv install --dev
Traceback (most recent call last):
  File "/home/travis/virtualenv/pypy3.5-5.10.1/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/home/travis/virtualenv/pypy3.5-5.10.1/site-packages/pipenv/__init__.py", line 47, in <module>
    from .cli import cli
  File "/home/travis/virtualenv/pypy3.5-5.10.1/site-packages/pipenv/cli/__init__.py", line 3, in <module>
    from .command import cli
  File "/home/travis/virtualenv/pypy3.5-5.10.1/site-packages/pipenv/cli/command.py", line 19, in <module>
    from .options import (
  File "/home/travis/virtualenv/pypy3.5-5.10.1/site-packages/pipenv/cli/options.py", line 11, in <module>
    from .. import environments
  File "/home/travis/virtualenv/pypy3.5-5.10.1/site-packages/pipenv/environments.py", line 7, in <module>
    from ._compat import fix_utf8
  File "/home/travis/virtualenv/pypy3.5-5.10.1/site-packages/pipenv/_compat.py", line 96, in <module>
    OUT_ENCODING, ERR_ENCODING = force_encoding()
  File "/home/travis/virtualenv/pypy3.5-5.10.1/site-packages/pipenv/_compat.py", line 66, in force_encoding
    from ctypes import pythonapi, py_object, c_char_p
ImportError: cannot import name 'pythonapi'```

**Comment by cclauss** [comment]
```
- python: pypy3.5-6.0
  dist: xenial
```
works as expected but the problem is https://github.com/python/typed_ast/issues/97#issuecomment-484337454 that __Pypy__ is not yet compatible with the dependency __typed-ast__.
