### ISSUE TITLE
Version 4.2 Character Encoding Issue on Python 2.7

### ISSUE THREAD

**Issue by williamdean** [sybrenstuvel/python-rsa#151]
```
root@debiantest:~# pip install rsa==4.2
Collecting rsa==4.2
  Downloading https://files.pythonhosted.org/packages/68/69/854f072529f9e0ed2cc97b81adc5f20a18dab60bc84dd0eec7446d2166df/rsa-4.2.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 4.8MB/s
Collecting pyasn1>=0.1.3 (from rsa==4.2)
  Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 7.2MB/s
Building wheels for collected packages: rsa
  Running setup.py bdist_wheel for rsa ... done
  Stored in directory: /root/.cache/pip/wheels/ea/90/b5/0d12df0b1ff2d5bafa07ef2840724609a6a09e815d69deb9cf
Successfully built rsa
Installing collected packages: pyasn1, rsa
Successfully installed pyasn1-0.4.8 rsa-4.2
root@debiantest:~# python2.7
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rsa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rsa/__init__.py", line 24, in <module>
    from rsa.key import newkeys, PrivateKey, PublicKey
  File "/usr/local/lib/python2.7/dist-packages/rsa/key.py", line 1
SyntaxError: Non-ASCII character '\xc3' in file /usr/local/lib/python2.7/dist-packages/rsa/key.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by williamdean** [comment]
Closing. I see that Python 2.7 support was dropped as on 4.1.x
