### ISSUE TITLE
rsa.sign return an AttributeError...

### ISSUE THREAD

**Issue by alifiroozi80** [sybrenstuvel/python-rsa#197]
Hello, 
I have a simple code that basically ancrypt and decrypt a message...
But when i use the **rsa.sign** to sign my message, it will return an AttributeError...
**Here is the code:**

```
import rsa



def generate_keys():
    public_key, private_key = rsa.newkeys(1024)
    with open('keys/publicKey.pem', 'wb') as p:
        p.write(public_key.save_pkcs1('PEM'))
    with open('keys/privateKey.pem', 'wb') as p:
        p.write(private_key.save_pkcs1('PEM'))


def load_keys():
    with open('keys/publicKey.pem', 'rb') as p:
        public_key = rsa.PublicKey.load_pkcs1(p.read())
    with open('keys/privateKey.pem', 'rb') as p:
        private_key = rsa.PrivateKey.load_pkcs1(p.read())
    return private_key, public_key


def encrypt(message, key):
    return rsa.encrypt(message.encode('ascii'), key)


def decrypt(ciphertext, key):
    try:
        return rsa.decrypt(ciphertext, key).decode('ascii')
    except TypeError as _:
        return False


def sign(message, key):
    return rsa.sign(message.encode('ascii'), key, 'SHA-1')


def verify(message, signature, key):
    try:
        return rsa.verify(message.encode('ascii'), signature, key, ) == 'SHA-1'
    except Exception as _:
        return False


generate_keys()
publicKey, privateKey = load_keys()

message = "Hello World!"
ciphertext = encrypt(message, publicKey)
print(ciphertext)
print("---------------------------------")
signature = sign(message, privateKey)
```

**Output:**

```
b'P\xcc\xfad\xb9cxa\xcb\xbfO\x8d\xcb\xb2\x8a\xae^\xcf\x93X~ \xe6\xee\xea\x03\x13z\xfe\xde=\\\x12\x89(X`o\xf0\xfes\xa4\xa4\xa0\xe9\xd55^\xa0\xaewP\xcb\xa0{T*\xa8=\xa6\xe8\xc2\xbe\xd4Y\x83\x89C\x8b\x03\xa7G\n\xcbuF\x91\xc1\xb3c\xd6O%?\x12O\x15\xd4\xb0\x05\xe0\x8f\xd4\x87.\x18@\x1d0\xdf\xff\xd4\xe9\x9ae*0\xa2\\/\x14|\xb4z\xd5\xaa\xb9-\x01\x84\xb1\x8eM\x95\x1c\x15Y6'
---------------------------------
Traceback (most recent call last):
  File "/home/ali/Desktop/pro/python-pro/encryption/main.py", line 53, in <module>
    signature = sign(message, privateKey)
  File "/home/ali/Desktop/pro/python-pro/encryption/main.py", line 34, in sign
    return rsa.sign(message.encode('ascii'), key, 'SHA-1')
  File "/home/ali/Desktop/pro/python-pro/encryption/venv/lib/python3.10/site-packages/rsa/pkcs1.py", line 338, in sign
    return sign_hash(msg_hash, priv_key, hash_method)
  File "/home/ali/Desktop/pro/python-pro/encryption/venv/lib/python3.10/site-packages/rsa/pkcs1.py", line 313, in sign_hash
    encrypted = priv_key.blinded_encrypt(payload)
AttributeError: 'PublicKey' object has no attribute 'blinded_encrypt'

```

**Comment by alifiroozi80** [comment]
Hey @myheroyuki
It is working now...
Such a stupid mistake🤪
Thanks bro👍
