### ISSUE TITLE
import openssl encrypted key

### ISSUE THREAD

**Issue by cyber-land** [sybrenstuvel/python-rsa#200]
if I try to open a private key generate from `openssl genrsa -out private-key.pem 2048` there are not problem but if I generate an encrypted key in that way `openssl genrsa -aes256 -out private-key.pem 2048` that code doesn't work anymore:

```python
with open('private-key.pem', mode='rb') as private_file:
    keydata = private_file.read()
    privkey = rsa.PrivateKey.load_pkcs1(keydata)
```

here to output:

```bash
Traceback (most recent call last):
  File "/home/michele/documents/rsa_.py", line 16, in <module>
    privkey = rsa.PrivateKey.load_pkcs1(keydata)
  File "/home/michele/.local/lib/python3.10/site-packages/rsa/key.py", line 124, in load_pkcs1
    return method(keyfile)
  File "/home/michele/.local/lib/python3.10/site-packages/rsa/key.py", line 612, in _load_pkcs1_pem
    return cls._load_pkcs1_der(der)
  File "/home/michele/.local/lib/python3.10/site-packages/rsa/key.py", line 526, in _load_pkcs1_der
    (priv, _) = decoder.decode(keyfile)
  File "/usr/lib/python3.10/site-packages/pyasn1/codec/ber/decoder.py", line 1581, in __call__
    value, substrate = concreteDecoder.valueDecoder(
  File "/usr/lib/python3.10/site-packages/pyasn1/codec/ber/decoder.py", line 73, in valueDecoder
    value, _ = decodeFun(head, asn1Spec, tagSet, length, **options)
  File "/usr/lib/python3.10/site-packages/pyasn1/codec/ber/decoder.py", line 1446, in __call__
    raise error.SubstrateUnderrunError('%d-octet short' % (length - len(substrate)))
pyasn1.error.SubstrateUnderrunError: 9100393396234518936636914659438529560627736-octet short
```

there should be a field for the AES password but I've found nothing

**Comment by sybrenstuvel** [comment]
It's quite simple: Python-RSA doesn't support encrypted keys. You'll have to decrypt the data yourself before passing it to `rsa.PrivateKey.load_pkcs1(keydata)`.
