### ISSUE TITLE
Not honoring --install-scripts?

### ISSUE THREAD

**Issue by sybrenstuvel** [sybrenstuvel/python-rsa#22]
Originally reported by: **Kimo Rosenbaum (Bitbucket: [kimor79](http://bitbucket.org/kimor79), GitHub: [kimor79](http://github.com/kimor79))**

----------------------------------------

I'm trying to install rsa via pip in Jenkins:

pip install \
    --build "${tmpdir}" \
    --install-option="--install-scripts=${WORKSPACE}/${MYDIR}/bin" \
    --requirement "${MYCHECKOUTDIR}/requirements.txt" \
    --target "${MYDIR}"

where tmpdir, MYDIR, MYCHECKOUTDIR, are directories relative to WORKSPACE (which is a Jenkins variable).

I've tried several combinations of --install-option formatting but I always get this error:

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/local/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1294, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 525, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1639, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/util.py", line 294, in renames
    shutil.move(old, new)
  File "/usr/local/lib/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/bin/pyrsa-decrypt'

Any suggestions?

----------------------------------------
- Bitbucket: https://bitbucket.org/sybren/python-rsa/issue/22

**Comment by sybrenstuvel** [comment]
Can't reproduce, closing due to inactivity of reporter.
