### ISSUE TITLE
DeprecationWarning in load_pem

### ISSUE THREAD

**Issue by sybrenstuvel** [sybrenstuvel/python-rsa#30]
Originally reported by: **John Hagen (Bitbucket: [johnthagen](http://bitbucket.org/johnthagen), GitHub: [johnthagen](http://github.com/johnthagen))**

----------------------------------------

The following code run with `-Werror` on Python 3.5.1:

    import rsa

    with open('key.pem', 'rb') as key_file:
        rsa.PrivateKey.load_pkcs1(key_file.read())

Results in:

    Traceback (most recent call last):
      File "C:/Users/John Hagen/PycharmProjects/test/test.py", line 4, in <module>
        rsa.PrivateKey.load_pkcs1(key_file.read())
      File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35\lib\site-    packages\rsa\key.py", line 65, in load_pkcs1
        return method(keyfile)
      File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35\lib\site-    packages\rsa\key.py", line 421, in _load_pkcs1_pem
        der = rsa.pem.load_pem(keyfile, b('RSA PRIVATE KEY'))
      File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35\lib\site-    packages\rsa\pem.py", line 92, in load_pem
        return base64.decodestring(pem)
      File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35\lib\base64.py",     line 560, in decodestring
        DeprecationWarning, 2)
    DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()

----------------------------------------
- Bitbucket: https://bitbucket.org/sybren/python-rsa/issue/30

**Comment by sybrenstuvel** [comment]
Reopening as there is still `base64.decodestring` used in two doctests.
