### ISSUE TITLE
How to use the private key in c#

### ISSUE THREAD

**Issue by 984958198** [sybrenstuvel/python-rsa#84]
Issues related to link: http://stackoverflow.com/questions/41330106/c-sharp-rsa-code-exported-python
```
>>> import rsa
>>> rsa.PrivateKey.load_pkcs1("BwIAAACkAABSU0EyAAQAAAEAAQDdmDDrHcqxUxzfTGLCtOnOwvD76nh+1ctJBGGquK6G2YyrlLRB3ZVRr1dy5PTqoEnVipV/qBHYfiTyD2rce/wrYV/iGFj3ETywdlr/wvAzRNwahr8VMOrs7iJItoiDoIsHuVXwpwXpJdWar4v5Gg+I2rD13PjYXSgF6Mkn2ANWnL0htMboQqJUnitEiO79iLx+1S+pbBlgzunnkkoX3u3O+jUG9NZPKuNrJOsRct4mF1b3dHU9pwu/c9jNN7aaRMuhdSxkqb32hllyIWxJuAcHOmfyVpt9b0aY6lK4FfeTcVuXlNhTkyLIT70AYvZN4hGvU7iFLXQEpwG6Owt2kuTE3cFKo7gX1hQgigsbJ7v7DOR7Ga98l3t7S4v9UCiSNNrFHjAQ23zYcZbMXXrehor0BYKwuzqP7TJ/eA4EozS4PAHZC665GfqjWNjARNXoBRvLWftDGQOA495QZZsrYY+Pop0TDDLow0PuSp/3neZecQu2V1taUJK5ZdafRRx4I3dqz9DcW3mUuIx53Sgifqdeu6lOcz0g8Z/9SamuN7f5uaoy7dE3YbANajidcz+UIaEaxeO9v717GqQ2XnULu46bAe2ApEbCV3582NbbCiPCg2p3azB0WxQc6cZmLS8XgcRXEviSGr9tJz2V4mt2QJHnr10jUDXzXYfUklMPv6RusPdj8WuRzsbPJ5bgyWqQVP55g5k3SFRjBG8TF6DzTWuqPC6ShLtnkgQ93HJxkqYRn39PVi0/H1LbVMk4H5vTzw0=")

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    rsa.PrivateKey.load_pkcs1("BwIAAACkAABSU0EyAAQAAAEAAQDdmDDrHcqxUxzfTGLCtOnOwvD76nh+1ctJBGGquK6G2YyrlLRB3ZVRr1dy5PTqoEnVipV/qBHYfiTyD2rce/wrYV/iGFj3ETywdlr/wvAzRNwahr8VMOrs7iJItoiDoIsHuVXwpwXpJdWar4v5Gg+I2rD13PjYXSgF6Mkn2ANWnL0htMboQqJUnitEiO79iLx+1S+pbBlgzunnkkoX3u3O+jUG9NZPKuNrJOsRct4mF1b3dHU9pwu/c9jNN7aaRMuhdSxkqb32hllyIWxJuAcHOmfyVpt9b0aY6lK4FfeTcVuXlNhTkyLIT70AYvZN4hGvU7iFLXQEpwG6Owt2kuTE3cFKo7gX1hQgigsbJ7v7DOR7Ga98l3t7S4v9UCiSNNrFHjAQ23zYcZbMXXrehor0BYKwuzqP7TJ/eA4EozS4PAHZC665GfqjWNjARNXoBRvLWftDGQOA495QZZsrYY+Pop0TDDLow0PuSp/3neZecQu2V1taUJK5ZdafRRx4I3dqz9DcW3mUuIx53Sgifqdeu6lOcz0g8Z/9SamuN7f5uaoy7dE3YbANajidcz+UIaEaxeO9v717GqQ2XnULu46bAe2ApEbCV3582NbbCiPCg2p3azB0WxQc6cZmLS8XgcRXEviSGr9tJz2V4mt2QJHnr10jUDXzXYfUklMPv6RusPdj8WuRzsbPJ5bgyWqQVP55g5k3SFRjBG8TF6DzTWuqPC6ShLtnkgQ93HJxkqYRn39PVi0/H1LbVMk4H5vTzw0=")
  File "E:\Python27\lib\site-packages\rsa\key.py", line 75, in load_pkcs1
    return method(keyfile)
  File "E:\Python27\lib\site-packages\rsa\key.py", line 510, in _load_pkcs1_pem
    der = rsa.pem.load_pem(keyfile, b('RSA PRIVATE KEY'))
  File "E:\Python27\lib\site-packages\rsa\pem.py", line 91, in load_pem
    raise ValueError('No PEM start marker "%s" found' % pem_start)
ValueError: No PEM start marker "-----BEGIN RSA PRIVATE KEY-----" found
```

**Comment by sybrenstuvel** [comment]
You're trying to load a key that is not in the expected format. What is your question?

**Comment by 984958198** [comment]
I know this is not a standard format of the private key, but it can identify in c #, I want to ask the rsa how to identify the non-standard format
```
PrivateKey = "BwIAAACkAABSU0EyAAQAAAEAAQDdmDDrHcqxUxzfTGLCtOnOwvD76nh+1ctJBGGquK6G2YyrlLRB3ZVRr1dy5PTqoEnVipV/qBHYfiTyD2rce/wrYV/iGFj3ETywdlr/wvAzRNwahr8VMOrs7iJItoiDoIsHuVXwpwXpJdWar4v5Gg+I2rD13PjYXSgF6Mkn2ANWnL0htMboQqJUnitEiO79iLx+1S+pbBlgzunnkkoX3u3O+jUG9NZPKuNrJOsRct4mF1b3dHU9pwu/c9jNN7aaRMuhdSxkqb32hllyIWxJuAcHOmfyVpt9b0aY6lK4FfeTcVuXlNhTkyLIT70AYvZN4hGvU7iFLXQEpwG6Owt2kuTE3cFKo7gX1hQgigsbJ7v7DOR7Ga98l3t7S4v9UCiSNNrFHjAQ23zYcZbMXXrehor0BYKwuzqP7TJ/eA4EozS4PAHZC665GfqjWNjARNXoBRvLWftDGQOA495QZZsrYY+Pop0TDDLow0PuSp/3neZecQu2V1taUJK5ZdafRRx4I3dqz9DcW3mUuIx53Sgifqdeu6lOcz0g8Z/9SamuN7f5uaoy7dE3YbANajidcz+UIaEaxeO9v717GqQ2XnULu46bAe2ApEbCV3582NbbCiPCg2p3azB0WxQc6cZmLS8XgcRXEviSGr9tJz2V4mt2QJHnr10jUDXzXYfUklMPv6RusPdj8WuRzsbPJ5bgyWqQVP55g5k3SFRjBG8TF6DzTWuqPC6ShLtnkgQ93HJxkqYRn39PVi0/H1LbVMk4H5vTzw0="
CryptText = "SiaZZW85CExq+2OEjfXiIldsivitxoS69xYlpTWrXyfFjU6GuIO+nmFYfdI06wDiKFU3Vcjoo5Nz2/7ooTFqEBVRun57GG6fw10c4BAkaMyUy2JiyLYnNtdDFv+sYdRuLfKW4cdNOeN0KEqMRZfPfmsGhYHIR2gYrS8kUZTG0Ds="
CryptText with PrivateKey will get after decryption: ZLeDWyfLHE7qSFBD
```

**Comment by sybrenstuvel** [comment]
So which format is the key in? You'll have to tell me; unfortunately I don't have the time to do all the research for you.

**Comment by 984958198** [comment]
Sorry, this problem I don't have until now, there is no way, hope to get help

**Comment by sybrenstuvel** [comment]
I would suggest reading the documentation of whatever C# thing you use, and figure out which format their keys are in. If they don't document it, ask the author(s). Someone will know. Once you have that, we can see how to build support for it in Python RSA.

**Comment by sybrenstuvel** [comment]
Please read the answer at http://stackoverflow.com/a/28290057/875379
