### ISSUE TITLE
cli Exception TypeError in Python3

### ISSUE THREAD

**Issue by zjuchenyuan** [sybrenstuvel/python-rsa#90]
in `cli.py`, there're some code like `sys.stdout.write(data)`

but in python3, exception occurs:

```
TypeError: write() argument must be str, not bytes
```

So, for better support python3, it's should be changed to 

```
sys.stdout.write(data.decode())
```

or

```
sys.stdout.write(repr(outdata)) #if outdata cannot be displayed as utf-8
```

----

besides, the input also should be changed from str to bytes:

```
class EncryptOperation(CryptoOperation):
    #...
    def perform_operation(self, indata, pub_key, cli_args=None):
        return rsa.encrypt(bytes(indata,encoding='utf-8'), pub_key)
```

**Comment by sybrenstuvel** [comment]
Where do you find this code? There is no `sys.stdout.write` anywhere in `cli.py`. Which version of the rsa library are you testing with?

**Comment by adamantike** [comment]
We use that in the compatibility layer (https://github.com/sybrenstuvel/python-rsa/blob/2d81e0fe4b89398876da8a9027d1465a5bb4434b/rsa/_compat.py#L59), but a Python 3 environment should never reach that line.

@zjuchenyuan can you provide a full stacktrace or the steps to reproduce it?

**Comment by zjuchenyuan** [comment]
I installed by using `pip install rsa`, and my platform is `win10`

```
c:\temp>pyrsa-keygen --pubout=pub.pub 1024
Generating 1024-bit key
Writing public key to pub.pub
Writing private key to stdout
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\pyrsa-keygen.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\rsa\cli.py", line 87, in keygen
    sys.stdout.write(data)
TypeError: write() argument must be str, not bytes
```

Thanks for your attention~

**Comment by zjuchenyuan** [comment]
`pip freeze` tells me that:

```
rsa==3.4.2
```

**Comment by adamantike** [comment]
The last release `3.4.2` (the one you are using) is missing commit fedcaa1, which fixes that scenario. However, I think it was not included in the release because it's not just a hotfix, and could have required a bump to version `3.5`.

As a cherrypick would be probably unwanted based on the commit's other changes, I think we should add a simpler commit just with the fix, and add it to `3.4.3`. What do you think @sybrenstuvel ?

**Comment by sybrenstuvel** [comment]
@adamantike I agree, let's make a `v3.4` branch to fix this, and release `3.4.3`.

**Comment by vstoykov** [comment]
There is version 4.0 out there should this be closed?
